### ISSUE TITLE
/usr/bin/python3

### ISSUE THREAD

**Issue by rahvee** [iusrepo/python36u#4] opened 2018-03-09 13:28 UTC
Is this a good way to reach the maintainers of the python35u and python36u packages? The problem is, starting in 35u and 36u, there is no `/usr/bin/python3`, which is a backward-breaking change. Previously, users could start scripts with `#!/usr/bin/env python3` but that is only possible up to python 3.4, because of this change in 35u and 36u. In order to use 35u or 36u, everybody will need to modify their scripts to use `/usr/bin/python3.5` or `/usr/bin/python3.6`, which is unrealistic because it's often not your own scripts that need to be changed. Scripts that get installed via yum, or from github, or anywhere else in the community... All the scripts in the world need to be hard-coded to a specific version of python...

I'm hoping you'll be willing to add a symlink `python3 -> python3.5` or `python3 -> python3.6` to the rpm packages...

**Comment by carlwgeorge** [comment] 2018-03-09 13:56
Duplicate of #2.

**Closed as completed by carlwgeorge** 2018-03-09 13:56 UTC
